-- Exec USP_GetUserDetailsOnSearch 'Jaipal'
CREATE PROCEDURE [dbo].[USP_GetUserDetailsOnSearch]
@Search NVARCHAR(200)
AS
BEGIN
	SELECT LAST_NAME+', '+FIRST_NAME AS DisplayName,
		EMPLOYEE_NUMBER, LAST_NAME, FIRST_NAME, START_DATE, TERMINATIONDATE, JOB_TITLE_DAILY, JOB_FAMILY, DIRECT_INDIRECT, SUPERVISOR_NUMBER, SUPERVISOR_NAME, LOCATION_NAME, LOCATION_CODE, COUNTRY_CODE, COUNTRY_NAME, ORGANIZATION_NAME, DIVISION_CODE, DIVISION_NAME, EMAIL_ADDRESS, AD_USERNAME, ASSIGNMENT_CATEGORY, SALARY_BASIS, ASSIGNMENT_STATUS
	From tbl_HRITMasterData WHERE 
	AD_USERNAME Like '%'+@Search+'%' OR
	EMAIL_ADDRESS Like '%'+@Search+'%' OR
	LAST_NAME +FIRST_NAME  Like '%'+@Search+'%' 
END