-- Exec USP_GetUserByLoginId 'jreddy'
CREATE PROCEDURE [dbo].[USP_GetUserByLoginId]
@LoginId nvarchar(100)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT LAST_NAME+', '+FIRST_NAME AS DisplayName,
		H.EMPLOYEE_NUMBER, H.LAST_NAME, H.FIRST_NAME, H.START_DATE, H.TERMINATIONDATE, H.JOB_TITLE_DAILY, H.JOB_FAMILY, H.DIRECT_INDIRECT, H.SUPERVISOR_NUMBER, H.SUPERVISOR_NAME, H.LOCATION_NAME, H.LOCATION_CODE, H.COUNTRY_CODE, H.COUNTRY_NAME, H.ORGANIZATION_NAME, H.DIVISION_CODE, H.DIVISION_NAME, H.EMAIL_ADDRESS, H.AD_USERNAME, H.ASSIGNMENT_CATEGORY, H.SALARY_BASIS, H.ASSIGNMENT_STATUS
	FROM tbl_HRITMasterData H
	WHERE H.AD_USERNAME = @LoginId
	
END