CREATE TABLE [dbo].[PurchaseOrder] (
    [Id]                     INT           IDENTITY (1, 1) NOT NULL,
    [Title]                  VARCHAR (50)  NOT NULL,
    [WorkFlowId]             INT           NULL,
    [RequestedBy]            VARCHAR (50)  NOT NULL,
    [DepartmentId]           INT           NOT NULL,
    [RequestingDepartmentId] INT           NOT NULL,
    [AFINumber]              VARCHAR (15)  NOT NULL,
    [VendorId]               INT           NOT NULL,
    [VendorNumber]           VARCHAR (50)  NOT NULL,
    [VendorEmail]            VARCHAR (100) NOT NULL,
    [VendorPhone]            VARCHAR (25)  NOT NULL,
    [VendorFax]              VARCHAR (25)  NOT NULL,
    [DeliveryDate]           DATETIME      NOT NULL,
    [VendorSelectionId]      INT           NOT NULL,
    [VendorReasonId]         INT           NULL,
    [RemarksId]              INT           NULL,
    [StatusId]               INT           NOT NULL,
    [VendorRemarksId]        INT           NULL,
    [CreatedBy]              VARCHAR (50)  NOT NULL,
    [CreatedOn]              DATETIME      NOT NULL,
    [ModifiedBy]             VARCHAR (50)  NOT NULL,
    [ModifiedOn]             DATETIME      NOT NULL,
    CONSTRAINT [PK_PurchaseOrder] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PurchaseOrder_Comments] FOREIGN KEY ([RemarksId]) REFERENCES [dbo].[Comments] ([Id]),
    CONSTRAINT [FK_PurchaseOrder_RequestingDepartments] FOREIGN KEY ([RequestingDepartmentId]) REFERENCES [dbo].[RequestingDepartments] ([Id]),
    CONSTRAINT [FK_PurchaseOrder_Status] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Status] ([Id]),
    CONSTRAINT [FK_PurchaseOrder_VendorReason] FOREIGN KEY ([VendorReasonId]) REFERENCES [dbo].[VendorReason] ([Id]),
    CONSTRAINT [FK_PurchaseOrder_VendorSelection] FOREIGN KEY ([VendorSelectionId]) REFERENCES [dbo].[VendorSelection] ([Id]),
    CONSTRAINT [FK_PurchaseOrder_VendRemarks] FOREIGN KEY ([VendorRemarksId]) REFERENCES [dbo].[Comments] ([Id])
);

